services:
  spiders:
    build:
        context: .
        dockerfile: Dockerfile.spiders
    volumes:
      - type: bind
        source: ./diarios_spiders/diarios
        target: /diarios_spiders/diarios