site_name: Squad-05 MDS
theme:
  name: material
nav:
  - Inicio: 'index.md'
  - Organização do Projeto:
    - Backlog: 'Organizacao do Projeto/Backlog.md'
    - Arquitetura: 'Organizacao do Projeto/Arquitetura.md'
    - Comunicação: 'Organizacao do Projeto/Comunicacao.md'
    - Story Map: 'Organizacao do Projeto/Storymap.md'
  - Tecnologias:
    - Escolhas Tecnológicas: 'Tecnologias/Tecnologias.md'
  - Protótipo: 'Prototipo/Prototipo.md'
  - Sprints:
    - Sprint00:
      - Planejamento: 'Sprints/Sprint00/Planejamentos00.md'
      - Resultados: 'Sprints/Sprint00/Resultados00.md'
    - Sprint01:
      - Planejamento: 'Sprints/Sprint01/Planejamentos01.md'
      - Resultados: 'Sprints/Sprint01/Resultados01.md'
    - Sprint02:
      - Planejamento: 'Sprints/Sprint02/Planejamentos02.md'
      - Resultados: 'Sprints/Sprint02/Resultados02.md'
    - Sprint03:
      - Planejamento: 'Sprints/Sprint03/Planejamentos03.md'
      - Resultados: 'Sprints/Sprint03/Resultados03.md'
    - Sprint04:
      - Planejamento: 'Sprints/Sprint04/Planejamentos04.md'
      - Resultados: 'Sprints/Sprint04/Resultados04.md'
    - Sprint05:
      - Planejamento: 'Sprints/Sprint05/Planejamentos05.md'
      - Resultados: 'Sprints/Sprint05/Resultados05.md'
    - Sprint06:
      - Planejamento: 'Sprints/Sprint06/Planejamentos06.md'
      - Resultados: 'Sprints/Sprint06/Resultados06.md'
    - Sprint07:
      - Planejamento: 'Sprints/Sprint07/Planejamentos07.md'
      - Resultados: 'Sprints/Sprint07/Resultados07.md'
    - Sprint08:
      - Planejamento: 'Sprints/Sprint08/Planejamentos08.md'
      - Resultados: 'Sprints/Sprint08/Resultados08.md'
    - Sprint09:
      - Planejamento: 'Sprints/Sprint09/Planejamentos09.md'
      - Resultados: 'Sprints/Sprint09/Resultados09.md'
    - Sprint10:
      - Planejamento: 'Sprints/Sprint10/Planejamentos10.md'
      - Resultados: 'Sprints/Sprint10/Resultados10.md'
    - Sprint11:
      - Planejamento: 'Sprints/Sprint11/Planejamentos11.md'
      - Resultados: 'Sprints/Sprint11/Resultados11.md'
  - Sobre: 'about.md'
